stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/wine.csv
    params:
      - prepare.test_size
      - prepare.random_state
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    params:
      - train.model_type
      - train.n_estimators
      - train.max_depth
      - train.random_state
    outs:
      - model.pkl